{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "nexus-chart.fullname" . }}-monitor
  labels:
    app.kubernetes.io/name: {{ include "nexus-chart.name" . }}
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nexus-chart.name" . }}
      app.kubernetes.io/component: controlplane
  endpoints:
    - port: metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
{{- end }}
