// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: cp.proto

package cp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeAddr      string                 `protobuf:"bytes,1,opt,name=node_addr,json=nodeAddr,proto3" json:"node_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_cp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_cp_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterNodeRequest) GetNodeAddr() string {
	if x != nil {
		return x.NodeAddr
	}
	return ""
}

type RegisterNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	LeaderId      string                 `protobuf:"bytes,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"` // if redirect is needed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_cp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_cp_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterNodeResponse) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

type GetTopologyRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CurrentVersion uint64                 `protobuf:"varint,1,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetTopologyRequest) Reset() {
	*x = GetTopologyRequest{}
	mi := &file_cp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopologyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopologyRequest) ProtoMessage() {}

func (x *GetTopologyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopologyRequest.ProtoReflect.Descriptor instead.
func (*GetTopologyRequest) Descriptor() ([]byte, []int) {
	return file_cp_proto_rawDescGZIP(), []int{2}
}

func (x *GetTopologyRequest) GetCurrentVersion() uint64 {
	if x != nil {
		return x.CurrentVersion
	}
	return 0
}

type GetTopologyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Nodes         []string               `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Ring          []uint32               `protobuf:"varint,3,rep,packed,name=ring,proto3" json:"ring,omitempty"`
	NodeMap       map[uint32]string      `protobuf:"bytes,4,rep,name=node_map,json=nodeMap,proto3" json:"node_map,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopologyResponse) Reset() {
	*x = GetTopologyResponse{}
	mi := &file_cp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopologyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopologyResponse) ProtoMessage() {}

func (x *GetTopologyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopologyResponse.ProtoReflect.Descriptor instead.
func (*GetTopologyResponse) Descriptor() ([]byte, []int) {
	return file_cp_proto_rawDescGZIP(), []int{3}
}

func (x *GetTopologyResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetTopologyResponse) GetNodes() []string {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *GetTopologyResponse) GetRing() []uint32 {
	if x != nil {
		return x.Ring
	}
	return nil
}

func (x *GetTopologyResponse) GetNodeMap() map[uint32]string {
	if x != nil {
		return x.NodeMap
	}
	return nil
}

var File_cp_proto protoreflect.FileDescriptor

const file_cp_proto_rawDesc = "" +
	"\n" +
	"\bcp.proto\x12\x02cp\"2\n" +
	"\x13RegisterNodeRequest\x12\x1b\n" +
	"\tnode_addr\x18\x01 \x01(\tR\bnodeAddr\"M\n" +
	"\x14RegisterNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\tR\bleaderId\"=\n" +
	"\x12GetTopologyRequest\x12'\n" +
	"\x0fcurrent_version\x18\x01 \x01(\x04R\x0ecurrentVersion\"\xd6\x01\n" +
	"\x13GetTopologyResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12\x14\n" +
	"\x05nodes\x18\x02 \x03(\tR\x05nodes\x12\x12\n" +
	"\x04ring\x18\x03 \x03(\rR\x04ring\x12?\n" +
	"\bnode_map\x18\x04 \x03(\v2$.cp.GetTopologyResponse.NodeMapEntryR\anodeMap\x1a:\n" +
	"\fNodeMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x98\x01\n" +
	"\x13ControlPlaneService\x12A\n" +
	"\fRegisterNode\x12\x17.cp.RegisterNodeRequest\x1a\x18.cp.RegisterNodeResponse\x12>\n" +
	"\vGetTopology\x12\x16.cp.GetTopologyRequest\x1a\x17.cp.GetTopologyResponseB#Z!github.com/imReese/NexusKV/pkg/cpb\x06proto3"

var (
	file_cp_proto_rawDescOnce sync.Once
	file_cp_proto_rawDescData []byte
)

func file_cp_proto_rawDescGZIP() []byte {
	file_cp_proto_rawDescOnce.Do(func() {
		file_cp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cp_proto_rawDesc), len(file_cp_proto_rawDesc)))
	})
	return file_cp_proto_rawDescData
}

var file_cp_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_cp_proto_goTypes = []any{
	(*RegisterNodeRequest)(nil),  // 0: cp.RegisterNodeRequest
	(*RegisterNodeResponse)(nil), // 1: cp.RegisterNodeResponse
	(*GetTopologyRequest)(nil),   // 2: cp.GetTopologyRequest
	(*GetTopologyResponse)(nil),  // 3: cp.GetTopologyResponse
	nil,                          // 4: cp.GetTopologyResponse.NodeMapEntry
}
var file_cp_proto_depIdxs = []int32{
	4, // 0: cp.GetTopologyResponse.node_map:type_name -> cp.GetTopologyResponse.NodeMapEntry
	0, // 1: cp.ControlPlaneService.RegisterNode:input_type -> cp.RegisterNodeRequest
	2, // 2: cp.ControlPlaneService.GetTopology:input_type -> cp.GetTopologyRequest
	1, // 3: cp.ControlPlaneService.RegisterNode:output_type -> cp.RegisterNodeResponse
	3, // 4: cp.ControlPlaneService.GetTopology:output_type -> cp.GetTopologyResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cp_proto_init() }
func file_cp_proto_init() {
	if File_cp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cp_proto_rawDesc), len(file_cp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cp_proto_goTypes,
		DependencyIndexes: file_cp_proto_depIdxs,
		MessageInfos:      file_cp_proto_msgTypes,
	}.Build()
	File_cp_proto = out.File
	file_cp_proto_goTypes = nil
	file_cp_proto_depIdxs = nil
}
